apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  aws_access_key_id: QUtJQTRMQ0lKVjY0T0g1MkJMNVY=
  aws_secret_access_key: Z0NCL2RMTmNhUFlUUnVkVU81ZTFuYjNCSWo2YnpxSjFQenJNQ2xWOA==
